### ISSUE TITLE
Cannot find module './components/frontpage'

### ISSUE THREAD

**Issue by scottstensland** [luiselizondo/blog-example#1]
getting this error ... seeing same error on node version 5.6.0 or 0.10.40

I was trying to follow your blog entry 

```
[http://www.luiselizondo.net/how-to-create-a-docker-node-js-mongodb-varnish-environment/](url)
```

below I give you stack error for each of these node versions

......  here is error while using node  0.10.40 ..................................

stens@kamchatka ~/other_src/blog-example $ npm start

> application-name@0.0.1 start /home/stens/other_src/blog-example
> node start.js

module.js:340
    throw err;
    ^
Error: Cannot find module './components/frontpage'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/stens/other_src/blog-example/start.js:21:10
    at Array.forEach (native)
    at Object.<anonymous> (/home/stens/other_src/blog-example/start.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! application-name@0.0.1 start: `node start.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the application-name@0.0.1 start script.
npm ERR! This is most likely a problem with the application-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls application-name
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-77-generic
npm ERR! command "/home/stens/node-v0.10.40/bin/node" "/home/stens/node-v0.10.40/bin/npm" "start"
npm ERR! cwd /home/stens/other_src/blog-example
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/stens/other_src/blog-example/npm-debug.log
npm ERR! not ok code 0
stens@kamchatka ~/other_src/blog-example $ 

............  below is same error while using node version 5.6.0 ..................................

stens@kamchatka ~/other_src/blog-example $ npm start

> application-name@0.0.1 start /home/stens/other_src/blog-example
> node start.js

module.js:341
    throw err;
    ^

Error: Cannot find module './components/frontpage'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /home/stens/other_src/blog-example/start.js:21:10
    at Array.forEach (native)
    at Object.<anonymous> (/home/stens/other_src/blog-example/start.js:20:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/home/stens/node-v5.6.0/bin/node" "/home/stens/node-v5.6.0/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! application-name@0.0.1 start: `node start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the application-name@0.0.1 start script 'node start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the application-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs application-name
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls application-name
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stens/other_src/blog-example/npm-debug.log
stens@kamchatka ~/other_src/blog-example $

**Comment by luiselizondo** [comment]
You need to run npm install. I don't know if you did. 

Luis Elizondo

**Comment by scottstensland** [comment]
Yes I did run npm install which completed fine with no errors.

**Comment by dixitk13** [comment]
I tried the same example and ran into the same issue!
